// <auto-generated />
using System;
using FacturationApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacturationApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330105950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FacturationApp.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tunis, Tunisie",
                            Name = "Ahmed Ben Ali",
                            Phone = "+216 71 123 456"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Sfax, Tunisie",
                            Name = "Société XYZ",
                            Phone = "+216 73 456 789"
                        });
                });

            modelBuilder.Entity("FacturationApp.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimbreFiscal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTTC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTVA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FacturationApp.Models.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalHT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTTC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTVA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TvaRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceHT")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("FacturationApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceHT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TvaRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ordinateur Portable",
                            PriceHT = 1500m,
                            TvaRate = 19m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Souris USB",
                            PriceHT = 25m,
                            TvaRate = 19m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clavier",
                            PriceHT = 45m,
                            TvaRate = 19m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Écran 24\"",
                            PriceHT = 350m,
                            TvaRate = 7m
                        });
                });

            modelBuilder.Entity("FacturationApp.Models.Invoice", b =>
                {
                    b.HasOne("FacturationApp.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FacturationApp.Models.InvoiceLine", b =>
                {
                    b.HasOne("FacturationApp.Models.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturationApp.Models.Product", "Product")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FacturationApp.Models.Client", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("FacturationApp.Models.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("FacturationApp.Models.Product", b =>
                {
                    b.Navigation("InvoiceLines");
                });
#pragma warning restore 612, 618
        }
    }
}
